name: Deploy Aura Botanica to GitHub Pages

on:
  push:
    branches:
      - main
      - nitanshu/engine-core
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Aura Botanica Static Site
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'aura-botanica'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
